window:
  opacity: 0.9
  padding:
    x: 10
    y: 10
  decorations: none

font:
  size: 12
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic
  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic

selection:
  save_to_clipboard: true
